### ISSUE TITLE
Roadmap do aprendizado

### ISSUE THREAD

**Issue by rafaelDev0ps** [rafamttz/go-road-to-master#1]
- [x] Variáveis
  - [x] Declaração 
  - [x] Tipos de variáveis
---
- [x] Estruturas de Controle
  - [x] If 
  - [x] For
  - [x] Switch
---
- [x] Funções
  - [x] Valores de retorno
  - [x] Parâmetros
  - [x] Defer
---
- [x] Estrutura de Dados
  - [x] Arrays
  - [x] Structs
  - [x] Maps
  - [x] Slices
---
- [x] Interfaces
  - [x] Atribuindo métodos em interfaces
---
- [x] Importações e dependências
---
- [x] Concorrência
  - [x] Canais
  - [x] Goroutines
---
- [x] Erros
---
- [x] Criando um server em Go
